BEGIN TRAN
	UPDATE [dbo].[RugbyTournaments] SET HasFixtureMatchNumber = 1, HasFixtureRoundName = 1 WHERE DataProvider = 2 AND ProviderTournamentId IN (850)
	------------------------------------------------------------------------------------------------------------------------------------------------
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 1 WHERE ProviderFixtureId = 20158500100
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 2 WHERE ProviderFixtureId = 20158500110
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 3 WHERE ProviderFixtureId = 20158500120
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 4 WHERE ProviderFixtureId = 20158500130
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 5 WHERE ProviderFixtureId = 20158500140
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 6 WHERE ProviderFixtureId = 20158500150
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 7 WHERE ProviderFixtureId = 20158500160
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 8 WHERE ProviderFixtureId = 20158500170
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 9 WHERE ProviderFixtureId = 20158500180
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 10 WHERE ProviderFixtureId = 20158500190
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 11 WHERE ProviderFixtureId = 20158500200
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 12 WHERE ProviderFixtureId = 20158500210
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 13 WHERE ProviderFixtureId = 20158500220
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 14 WHERE ProviderFixtureId = 20158500230
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 15 WHERE ProviderFixtureId = 20158500240
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 16 WHERE ProviderFixtureId = 20158500250
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 17 WHERE ProviderFixtureId = 20158500260
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 18 WHERE ProviderFixtureId = 20158500270
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 19 WHERE ProviderFixtureId = 20158500280
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 20 WHERE ProviderFixtureId = 20158500290
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 21 WHERE ProviderFixtureId = 20158500300
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 22 WHERE ProviderFixtureId = 20158500310
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 23 WHERE ProviderFixtureId = 20158500320
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 24 WHERE ProviderFixtureId = 20158500330
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 25 WHERE ProviderFixtureId = 20158500340
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 26 WHERE ProviderFixtureId = 20158500350
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 27 WHERE ProviderFixtureId = 20158500360
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 28 WHERE ProviderFixtureId = 20158500370
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 29 WHERE ProviderFixtureId = 20158500380
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 30 WHERE ProviderFixtureId = 20158500390
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 31 WHERE ProviderFixtureId = 20158500400
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 32 WHERE ProviderFixtureId = 20158500410
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 33 WHERE ProviderFixtureId = 20158500420
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 34 WHERE ProviderFixtureId = 20158500430
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 35 WHERE ProviderFixtureId = 20158500440
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 36 WHERE ProviderFixtureId = 20158500450
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 37 WHERE ProviderFixtureId = 20158500460
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 38 WHERE ProviderFixtureId = 20158500470
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 39 WHERE ProviderFixtureId = 20158500480
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 40 WHERE ProviderFixtureId = 20158500490
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 41 WHERE ProviderFixtureId = 20158500500
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 42 WHERE ProviderFixtureId = 20158500510
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 43 WHERE ProviderFixtureId = 20158500520
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 44 WHERE ProviderFixtureId = 20158500540
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 45 WHERE ProviderFixtureId = 20158500610
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 46 WHERE ProviderFixtureId = 20158500620
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 47 WHERE ProviderFixtureId = 20158500710
	UPDATE [SuperSportDataEngine_PublicSportData].[dbo].[RugbyFixtures] SET MatchNumberCmsOverride = 48 WHERE ProviderFixtureId = 20158500720
COMMIT