#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class AwaitingJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");










            
            #line 10 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.AwaitingJobsPage_Title);

    int from, perPage;
    var filter = Query("filter");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    List<string> jobIds = null;
    Pager pager = null;

    using (var connection = Storage.GetConnection())
    {
        var storageConnection = connection as JobStorageConnection;

        if (storageConnection != null)
        {
            pager = new Pager(from, perPage, storageConnection.GetSetCount("awaiting"), null, DefaultRecordsPerPage);
            jobIds = storageConnection.GetRangeFromSet("awaiting", pager.FromRecord, pager.FromRecord + pager.RecordsPerPage - 1);
        }
    }


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 36 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        <h1 class=\"page-header\">");


            
            #line 39 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                           Write(Strings.AwaitingJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n");


            
            #line 41 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
         if (jobIds == null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\n                <h4>");


            
            #line 44 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
               Write(Strings.AwaitingJobsPage_ContinuationsWarning_Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\n                <p>");


            
            #line 45 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
              Write(Strings.AwaitingJobsPage_ContinuationsWarning_Text);

            
            #line default
            #line hidden
WriteLiteral("</p>\n            </div>\n");


            
            #line 47 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
        }
        else if (jobIds.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\n                <div class=\"btn-toolbar bt" +
"n-toolbar-top\">\n                    <button class=\"js-jobs-list-command btn btn-" +
"sm btn-primary\"\n                            data-url=\"");


            
            #line 53 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                 Write(Url.To("/jobs/awaiting/enqueue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 54 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\">\n                        <span class=\"glyphicon glyphicon-repeat\"></span>\n     " +
"                   ");


            
            #line 56 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                   Write(Strings.Common_EnqueueButton_Text);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n\n                    <button class=\"js-jobs-list-c" +
"ommand btn btn-sm btn-default\"\n                            data-url=\"");


            
            #line 60 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                 Write(Url.To("/jobs/awaiting/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 61 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                          Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-confirm=\"");


            
            #line 62 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                     Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\">\n                        <span class=\"glyphicon glyphicon-remove\"></span>\n     " +
"                   ");


            
            #line 64 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                   Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral(@"
                    </button>

                </div>

                <div class=""table-responsive"">
                    <table class=""table table-hover"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th class=""min-width"">");


            
            #line 76 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                 Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                              <th>");


            
            #line 77 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                             Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 78 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                 if (DisplayArgumentsInLists)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <th class=\"min-width\">");


            
            #line 80 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                     Write(Strings.Common_Arguments);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 81 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <th class=\"min-width\">");


            
            #line 82 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                 Write(Strings.AwaitingJobsPage_Table_Options);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th class=\"min-width\">");


            
            #line 83 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                 Write(Strings.AwaitingJobsPage_Table_Parent);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th class=\"align-right\">");


            
            #line 84 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                   Write(Strings.Common_Created);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            </tr>\n                        </thead>\n        " +
"                <tbody>\n");


            
            #line 88 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                             foreach (var jobId in jobIds)
                            {
                                JobData jobData;
                                StateData stateData;
                                StateData parentStateData = null;

                                using (var connection = Storage.GetConnection())
                                {
                                    jobData = connection.GetJobData(jobId);
                                    stateData = connection.GetStateData(jobId);

                                    if (stateData != null && stateData.Name == AwaitingState.StateName)
                                    {
                                        parentStateData = connection.GetStateData(stateData.Data["ParentId"]);
                                    }
                                }


            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row ");


            
            #line 105 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                        Write(jobData != null ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                    <td>\n                                     " +
"   <input type=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 107 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                                                                             Write(jobId);

            
            #line default
            #line hidden
WriteLiteral("\" />\n                                    </td>\n                                  " +
"  <td class=\"min-width\">\n                                        ");


            
            #line 110 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                   Write(Html.JobIdLink(jobId));

            
            #line default
            #line hidden
WriteLiteral("\n                                    </td>\n");


            
            #line 112 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                     if (jobData == null)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td colspan=\"");


            
            #line 114 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                 Write(DisplayArgumentsInLists ? 5 : 4);

            
            #line default
            #line hidden
WriteLiteral("\"><em>");


            
            #line 114 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                                                        Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em></td>\n");


            
            #line 115 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td class=\"word-break\">\n                 " +
"                           ");


            
            #line 119 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                       Write(Html.JobNameLink(jobId, jobData.Job));

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 120 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                           if (DisplayArgumentsInLists)
                                          {

            
            #line default
            #line hidden
WriteLiteral("                                              <td class=\"ellipsis ellipsis-wrap\">" +
"\n                                                    ");


            
            #line 123 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                               Write(Html.JobArguments(jobData.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                                </td>\n");


            
            #line 125 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                          }

            
            #line default
            #line hidden
WriteLiteral("                                        </td>\n");



WriteLiteral("                                        <td class=\"min-width\">\n");


            
            #line 128 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                             if (stateData != null && stateData.Data.ContainsKey("Options") && !String.IsNullOrWhiteSpace(stateData.Data["Options"]))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <code>");


            
            #line 130 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                 Write(stateData.Data["Options"]);

            
            #line default
            #line hidden
WriteLiteral("</code>\n");


            
            #line 131 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <em>");


            
            #line 134 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                               Write(Strings.Common_NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("</em>\n");


            
            #line 135 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </td>\n");



WriteLiteral("                                        <td class=\"min-width\">\n");


            
            #line 138 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                             if (parentStateData != null)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <a href=\"");


            
            #line 140 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                    Write(Url.JobDetails(stateData.Data["ParentId"]));

            
            #line default
            #line hidden
WriteLiteral("\">\n                                                    <span class=\"label label-d" +
"efault label-hover\" style=\"");


            
            #line 141 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                                                                     Write($"background-color: {JobHistoryRenderer.GetForegroundStateColor(parentStateData.Name)};");

            
            #line default
            #line hidden
WriteLiteral("\">\n                                                        ");


            
            #line 142 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                                   Write(parentStateData.Name);

            
            #line default
            #line hidden
WriteLiteral("\n                                                    </span>\n                    " +
"                            </a>\n");


            
            #line 145 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <em>");


            
            #line 148 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                               Write(Strings.Common_NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("</em>\n");


            
            #line 149 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </td>\n");



WriteLiteral("                                        <td class=\"min-width align-right\">\n      " +
"                                      ");


            
            #line 152 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                       Write(Html.RelativeTime(jobData.CreatedAt));

            
            #line default
            #line hidden
WriteLiteral("\n                                        </td>\n");


            
            #line 154 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\n");


            
            #line 156 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\n                    </table>\n                </d" +
"iv>\n              <div class=\"btn-toolbar\">\n                  ");


            
            #line 161 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
             Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              \n                  ");


            
            #line 163 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
             Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              </div>\n            </div>\n");


            
            #line 166 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\n                ");


            
            #line 170 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
           Write(Strings.AwaitingJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");


            
            #line 172 "..\..\Dashboard\Pages\AwaitingJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
