#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DeletedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");






            
            #line 6 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.DeletedJobsPage_Title);

    int from, perPage;
    var filter = Query("filter");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, monitor.DeletedListCount(filter), filter, DefaultRecordsPerPage);
    var jobs = monitor.DeletedJobs(pager.FromRecord, pager.RecordsPerPage, filter);


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 22 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        <h1 class=\"page-header\">");


            
            #line 25 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                           Write(Strings.DeletedJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n");


            
            #line 27 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\n                ");


            
            #line 30 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
           Write(Strings.DeletedJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");


            
            #line 32 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\n                <div class=\"btn-toolbar bt" +
"n-toolbar-top\">\n                    <button class=\"js-jobs-list-command btn btn-" +
"sm btn-primary\"\n                            data-url=\"");


            
            #line 38 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                 Write(Url.To("/jobs/deleted/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 39 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            disabled=\"disabled\">\n                        <span " +
"class=\"glyphicon glyphicon-repeat\"></span>\n                        ");


            
            #line 42 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                   Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n");


            
            #line 44 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                   if (true)
                  {
                      
            
            #line default
            #line hidden
            
            #line 46 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                 Write(Html.Filter(pager));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                         
                  }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>
                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th class=""min-width"">");


            
            #line 56 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                 Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th>");


            
            #line 57 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                               Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 58 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                 if (DisplayArgumentsInLists)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <th class=\"min-width\">");


            
            #line 60 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                     Write(Strings.Common_Arguments);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 61 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <th class=\"align-right\">");


            
            #line 62 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                   Write(Strings.DeletedJobsPage_Table_Deleted);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            </tr>\n                        </thead>\n        " +
"                <tbody>\n");


            
            #line 66 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                             foreach (var job in jobs)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row ");


            
            #line 68 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                        Write(job.Value == null || !job.Value.InDeletedState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 68 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                                                                                                   Write(job.Value != null && job.Value.InDeletedState && job.Value != null ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                    <td>\n");


            
            #line 70 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                         if (job.Value == null || job.Value.InDeletedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input type=\"checkbox\" class=\"js-jobs" +
"-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 72 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                                                                                 Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\n");


            
            #line 73 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n                                    <td" +
" class=\"min-width\">\n                                        ");


            
            #line 76 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                   Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 77 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                         if (job.Value != null && !job.Value.InDeletedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span title=\"");


            
            #line 79 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                    Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\n");


            
            #line 80 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n\n");


            
            #line 83 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                     if (job.Value == null)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <td colspan=\"");


            
            #line 85 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                 Write(DisplayArgumentsInLists ? 3 : 2);

            
            #line default
            #line hidden
WriteLiteral("\"><em>");


            
            #line 85 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                                                        Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em></td>\n");


            
            #line 86 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                      <td class=\"word-break\">\n                   " +
"                     ");


            
            #line 90 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                   Write(Html.JobNameLink(job.Key, monitor.JobDetails(job.Key).Properties["RecurringJobId"], job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                      </td>\n");


            
            #line 92 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                      if (DisplayArgumentsInLists)
                                      {

            
            #line default
            #line hidden
WriteLiteral("                                            <td class=\"ellipsis ellipsis-wrap\">\n " +
"                                               ");


            
            #line 95 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                           Write(Html.JobArguments(job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                            </td>\r\n");


            
            #line 97 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                      }

            
            #line default
            #line hidden
WriteLiteral("                                      <td class=\"align-right\">\n");


            
            #line 99 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                           if (job.Value.DeletedAt.HasValue)
                                          {
                                              
            
            #line default
            #line hidden
            
            #line 101 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                         Write(Html.RelativeTime(job.Value.DeletedAt.Value));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                                                                           
                                          }

            
            #line default
            #line hidden
WriteLiteral("                                      </td>\n");


            
            #line 104 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\n");


            
            #line 106 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\n                    </table>\n                </d" +
"iv>\n\n              <div class=\"btn-toolbar\">\n                  ");


            
            #line 112 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
             Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              \n                  ");


            
            #line 114 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
             Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              </div>\n            </div>\n");


            
            #line 117 "..\..\Dashboard\Pages\DeletedJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>\n\n");


        }
    }
}
#pragma warning restore 1591
