#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class FailedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");







            
            #line 7 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.FailedJobsPage_Title);

    int from, perPage;
    var filter = Query("filter");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, monitor.FailedCount(filter), filter, DefaultRecordsPerPage);
    var failedJobs = monitor.FailedJobs(pager.FromRecord, pager.RecordsPerPage, filter);


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 23 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        <h1 class=\"page-header\">");


            
            #line 26 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                           Write(Strings.FailedJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n");


            
            #line 28 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-success\">\n               ");


            
            #line 31 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
          Write(Strings.FailedJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");


            
            #line 33 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\n                ");


            
            #line 37 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.Raw(Strings.FailedJobsPage_FailedJobsNotExpire_Warning_Html));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");


            
            #line 39 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
            

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\n                <div class=\"btn-toolbar bt" +
"n-toolbar-top\">\n                    <button class=\"js-jobs-list-command btn btn-" +
"sm btn-primary\"\n                            data-url=\"");


            
            #line 43 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 Write(Url.To("/jobs/failed/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 44 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            disabled=\"disabled\">\n                        <span " +
"class=\"glyphicon glyphicon-repeat\"></span>\n                        ");


            
            #line 47 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                   Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n\n                    <button class=\"js-jobs-list-c" +
"ommand btn btn-sm btn-default\"\n                            data-url=\"");


            
            #line 51 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 Write(Url.To("/jobs/failed/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 52 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                          Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-confirm=\"");


            
            #line 53 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\">\n                        <span class=\"glyphicon glyphicon-remove\"></span>\n     " +
"                   ");


            
            #line 55 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                   Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n\n");


            
            #line 58 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                   if (true)
                  {
                      
            
            #line default
            #line hidden
            
            #line 60 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                 Write(Html.Filter(pager));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         
                  }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th class=""min-width"">");


            
            #line 71 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                 Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th>");


            
            #line 72 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               Write(Strings.FailedJobsPage_Table_Failed);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th>");


            
            #line 73 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 74 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 if (DisplayArgumentsInLists)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <th class=\"min-width\">");


            
            #line 76 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                     Write(Strings.Common_Arguments);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 77 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tr>\n                        </thead>\n              " +
"          <tbody>\n");


            
            #line 81 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               var index = 0; 

            
            #line default
            #line hidden

            
            #line 82 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                             foreach (var job in failedJobs)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row ");


            
            #line 84 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                        Write(!job.Value.InFailedState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 84 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                             Write(job.Value.InFailedState ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                    <td rowspan=\"");


            
            #line 85 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                             Write(job.Value.InFailedState ? "2" : "1");

            
            #line default
            #line hidden
WriteLiteral("\">\n");


            
            #line 86 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (job.Value.InFailedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input type=\"checkbox\" class=\"js-jobs" +
"-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 88 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                                 Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\n");


            
            #line 89 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n                                    <td" +
" class=\"min-width\" rowspan=\"");


            
            #line 91 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                               Write(job.Value.InFailedState ? "2" : "1");

            
            #line default
            #line hidden
WriteLiteral("\">\n                                        ");


            
            #line 92 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                   Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 93 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (!job.Value.InFailedState)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span title=\"");


            
            #line 95 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                    Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\n");


            
            #line 96 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n                                    <td" +
" class=\"min-width\">\n");


            
            #line 99 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (job.Value.FailedAt.HasValue)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 101 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                       Write(Html.RelativeTime(job.Value.FailedAt.Value));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                        
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n                                    <td" +
">\n                                        <div class=\"word-break\">\n             " +
"                             ");


            
            #line 106 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     Write(Html.JobNameLink(job.Key, monitor.JobDetails(job.Key).Properties["RecurringJobId"], job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                        </div>\n");


            
            #line 108 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         if (!String.IsNullOrEmpty(job.Value.ExceptionMessage))
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div style=\"color: #888;\">\n          " +
"                                      ");


            
            #line 111 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(job.Value.Reason);

            
            #line default
            #line hidden
WriteLiteral(" <a class=\"expander\" href=\"#\">");


            
            #line 111 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                           Write(index == 0 ? Strings.Common_LessDetails : Strings.Common_MoreDetails);

            
            #line default
            #line hidden
WriteLiteral("</a>\n                                            </div>\n");


            
            #line 113 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n                                </tr>\n");


            
            #line 116 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                if (job.Value.InFailedState)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\n                                        " +
"<td colspan=\"2\" class=\"failed-job-details\">\n                                    " +
"        <div class=\"expandable\" style=\"");


            
            #line 120 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                       Write(index++ == 0 ? "display: block;" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                                <h4>");


            
            #line 121 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                               Write(job.Value.ExceptionType);

            
            #line default
            #line hidden
WriteLiteral("</h4>\n                                                <p class=\"text-muted\">\n    " +
"                                                ");


            
            #line 123 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                               Write(job.Value.ExceptionMessage);

            
            #line default
            #line hidden
WriteLiteral("\n                                                </p>\n\n");


            
            #line 126 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                 if (!String.IsNullOrEmpty(job.Value.ExceptionDetails))
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <pre class=\"stack-trace\"><cod" +
"e>");


            
            #line 128 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                              Write(Html.StackTrace(job.Value.ExceptionDetails));

            
            #line default
            #line hidden
WriteLiteral("</code></pre>\n");


            
            #line 129 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </div>\n                              " +
"          </td>\n                                    </tr>\n");


            
            #line 133 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\n                    </table>\n                </d" +
"iv>\n\n              <div class=\"btn-toolbar\">\n                  ");


            
            #line 140 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
             Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n                  \n                  ");


            
            #line 142 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
             Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              </div>\n            </div>\n");


            
            #line 145 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>");


        }
    }
}
#pragma warning restore 1591
