#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    using System;
    
    #line 2 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class FetchedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");








            
            #line 8 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
  
    Layout = new LayoutPage(Queue.ToUpperInvariant());

    int from, perPage;
    var filter = Query("filter");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, monitor.FetchedCount(Queue, filter), filter, DefaultRecordsPerPage);
    var fetchedJobs = monitor.FetchedJobs(Queue, pager.FromRecord, pager.RecordsPerPage, filter);


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 24 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        ");


            
            #line 27 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
   Write(Html.Breadcrumbs(Strings.FetchedJobsPage_Title, new Dictionary<string, string>
        {
            { "Queues", Url.LinkToQueues() },
            { Queue.ToUpperInvariant(), Url.Queue(Queue) }
        }));

            
            #line default
            #line hidden
WriteLiteral("\n\n        <h1 class=\"page-header\">\n            ");


            
            #line 34 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
       Write(Queue.ToUpperInvariant());

            
            #line default
            #line hidden
WriteLiteral(" <small>");


            
            #line 34 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                        Write(Strings.FetchedJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</small>\n        </h1>\n\n");


            
            #line 37 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"alert alert-info\">\n            ");


            
            #line 40 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
       Write(Strings.FetchedJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n");


            
            #line 42 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"js-jobs-list\">\n            <div class=\"btn-toolbar btn-toolba" +
"r-top\">\n                <button class=\"js-jobs-list-command btn btn-sm btn-prima" +
"ry\"\n                        data-url=\"");


            
            #line 48 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                             Write(Url.To("/jobs/enqueued/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                        data-loading-text=\"");


            
            #line 49 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                      Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\n                        disabled=\"disabled\">\n                    <span class=\"g" +
"lyphicon glyphicon-repeat\"></span>\n                    ");


            
            #line 52 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
               Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\n                </button>\n\n                <button class=\"js-jobs-list-command b" +
"tn btn-sm btn-default\"\n                        data-url=\"");


            
            #line 56 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                             Write(Url.To("/jobs/enqueued/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                        data-loading-text=\"");


            
            #line 57 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                      Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\n                        data-confirm=\"");


            
            #line 58 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                 Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\"\n                        disabled=\"disabled\">\n                    <span class=\"g" +
"lyphicon glyphicon-remove\"></span>\n                    ");


            
            #line 61 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
               Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral("\n                </button>\n\n                ");


            
            #line 64 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
           Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>

            <div class=""table-responsive"">
                <table class=""table"">
                    <thead>
                        <tr>
                            <th class=""min-width"">
                                <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                            </th>
                            <th class=""min-width"">");


            
            #line 74 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                             Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            <th class=\"min-width\">");


            
            #line 75 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                             Write(Strings.Common_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            <th>");


            
            #line 76 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                           Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            <th class=\"align-right\">");


            
            #line 77 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                               Write(Strings.Common_Fetched);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                        </tr>\n                    </thead>\n                " +
"    <tbody>\n");


            
            #line 81 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                         foreach (var job in fetchedJobs)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row hover ");


            
            #line 83 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                                          Write(job.Value == null ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                <td>\n");


            
            #line 85 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                     if (job.Value != null)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input type=\"checkbox\" class=\"js-jobs-lis" +
"t-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 87 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                                                                                             Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\n");


            
            #line 88 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\n                                <td class=\"" +
"min-width\">\n                                  ");


            
            #line 91 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                             Write(Html.JobNameLink(job.Key, monitor.JobDetails(job.Key).Properties["RecurringJobId"], job.Value?.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                </td>\n");


            
            #line 93 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                 if (job.Value == null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td colspan=\"3\"><em>");


            
            #line 95 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                                   Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em></td>\n");


            
            #line 96 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td class=\"min-width\">\n                      " +
"                  ");


            
            #line 100 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                   Write(Html.StateLabel(job.Value.State));

            
            #line default
            #line hidden
WriteLiteral("\n                                    </td>\n");



WriteLiteral("                                    <td class=\"word-break\">\n                     " +
"                   ");


            
            #line 103 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                   Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                    </td>\n");



WriteLiteral("                                    <td class=\"align-right\">\n");


            
            #line 106 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                         if (job.Value.FetchedAt.HasValue)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 108 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                       Write(Html.RelativeTime(job.Value.FetchedAt.Value));

            
            #line default
            #line hidden
            
            #line 108 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                                                                         
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\n");


            
            #line 111 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tr>\n");


            
            #line 113 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\n                </table>\n            </div>\n\n       " +
"     ");


            
            #line 118 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
       Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n");


            
            #line 120 "..\..\Dashboard\Pages\FetchedJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>");


        }
    }
}
#pragma warning restore 1591
