#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.Linq;
    
    #line 4 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");








WriteLiteral("<!DOCTYPE html>\n<html lang=\"");


            
            #line 10 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\">\n<head>\n    <title>");


            
            #line 12 "..\..\Dashboard\Pages\LayoutPage.cshtml"
      Write(Title);

            
            #line default
            #line hidden
WriteLiteral(" - Hangfire</title>\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n   " +
" <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, i" +
"nitial-scale=1.0\">\n");


            
            #line 16 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       var version = GetType().GetTypeInfo().Assembly.GetName().Version; 

            
            #line default
            #line hidden
WriteLiteral("    <link rel=\"stylesheet\" href=\"");


            
            #line 17 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                            Write(Url.To($"/css{version.Major}{version.Minor}{version.Build}"));

            
            #line default
            #line hidden
WriteLiteral("\">\n</head>\n    <body>\n        <!-- Wrap all page content here -->\n        <div id" +
"=\"wrap\">\n\n            <!-- Fixed navbar -->\n            <div class=\"navbar navba" +
"r-default navbar-fixed-top\">\n              <div class=\"");


            
            #line 25 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                      Write(UseFullWidth ? "container-fluid" : "container");

            
            #line default
            #line hidden
WriteLiteral(@""">
                    <div class=""navbar-header"">
                        <button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target="".navbar-collapse"">
                            <span class=""icon-bar""></span>
                            <span class=""icon-bar""></span>
                            <span class=""icon-bar""></span>
                        </button>
                        <a class=""navbar-brand"" href=""");


            
            #line 32 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                                 Write(Url.Home());

            
            #line default
            #line hidden
WriteLiteral("\">Hangfire Dashboard</a>\n                    </div>\n                    <div clas" +
"s=\"collapse navbar-collapse\">\n                        ");


            
            #line 35 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                   Write(Html.RenderPartial(new Navigation()));

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 36 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                         if(@AppPath != null) {

            
            #line default
            #line hidden
WriteLiteral("                            <ul class=\"nav navbar-nav navbar-right\">\n            " +
"                    <li>\n                                    <a href=\"");


            
            #line 39 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                        Write(AppPath);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                        <span class=\"glyphicon glyphicon-log-o" +
"ut\"></span>\n                                        ");


            
            #line 41 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                   Write(Strings.LayoutPage_Back);

            
            #line default
            #line hidden
WriteLiteral("\n                                    </a>\n                                </li>\n " +
"                           </ul>\n");


            
            #line 45 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\n                    <!--/.nav-collapse -->\n           " +
"     </div>\n            </div>\n\n            <!-- Begin page content -->\n        " +
"  <div class=\"");


            
            #line 52 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                  Write(UseFullWidth ? "container-fluid" : "container");

            
            #line default
            #line hidden
WriteLiteral("\" style=\"margin-bottom: 20px;\">\n                ");


            
            #line 53 "..\..\Dashboard\Pages\LayoutPage.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n\n        <div id=\"footer\">\n          <div clas" +
"s=\"");


            
            #line 58 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                  Write(UseFullWidth ? "container-fluid" : "container");

            
            #line default
            #line hidden
WriteLiteral("\">\n                <ul class=\"list-inline credit\">\n                    <li>\n     " +
"                   <a href=\"https://www.hangfire.io/\" target=\"_blank\" rel=\"noope" +
"ner noreferrer\">Hangfire ");


            
            #line 61 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                                                                                          Write($"{version.Major}.{version.Minor}.{version.Build}");

            
            #line default
            #line hidden
WriteLiteral("\n                        </a>\n                    </li>\n");


            
            #line 64 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                     if(DashboardOptions.DisplayStorageConnectionString){

            
            #line default
            #line hidden
WriteLiteral("                    <li>");


            
            #line 65 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                   Write(Storage);

            
            #line default
            #line hidden
WriteLiteral("</li>\n");


            
            #line 66 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <li>");


            
            #line 67 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                   Write(Strings.LayoutPage_Footer_Time);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 67 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                                   Write(Html.LocalTime(DateTime.UtcNow));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                    <li>");


            
            #line 68 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                   Write(String.Format(Strings.LayoutPage_Footer_Generatedms, GenerationTime.Elapsed.TotalMilliseconds.ToString("N")));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                </ul>\n            </div>\n        </div>\n        \n        <d" +
"iv id=\"hangfireConfig\"\n             data-pollinterval=\"");


            
            #line 74 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                           Write(DashboardOptions.StatsPollingInterval);

            
            #line default
            #line hidden
WriteLiteral("\"\n             data-pollurl=\"");


            
            #line 75 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                       Write(Url.To("/stats"));

            
            #line default
            #line hidden
WriteLiteral("\">\n        </div>\n\n        <script src=\"");


            
            #line 78 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                Write(Url.To($"/js{version.Major}{version.Minor}{version.Build}"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\n    </body>\n</html>\n");


        }
    }
}
#pragma warning restore 1591
