#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ScheduledJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");






            
            #line 6 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
  
    Layout = new LayoutPage(Strings.ScheduledJobsPage_Title);

    int from, perPage;
    var filter = Query("filter");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, monitor.ScheduledCount(filter), filter, DefaultRecordsPerPage);
    var scheduledJobs = monitor.ScheduledJobs(pager.FromRecord, pager.RecordsPerPage, filter);


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 22 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        <h1 class=\"page-header\">");


            
            #line 25 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                           Write(Strings.ScheduledJobsPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n");


            
            #line 27 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\n                ");


            
            #line 30 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
           Write(Strings.ScheduledJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");


            
            #line 32 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\n                <div class=\"btn-toolbar bt" +
"n-toolbar-top\">\n                    <button class=\"js-jobs-list-command btn btn-" +
"sm btn-primary\"\n                            data-url=\"");


            
            #line 38 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                 Write(Url.To("/jobs/scheduled/enqueue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 39 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            disabled=\"disabled\">\n                        <span " +
"class=\"glyphicon glyphicon-play\"></span>\n                        ");


            
            #line 42 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                   Write(Strings.ScheduledJobsPage_EnqueueNow);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n\n                    <button class=\"js-jobs-list-c" +
"ommand btn btn-sm btn-default\"\n                            data-url=\"");


            
            #line 46 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                 Write(Url.To("/jobs/scheduled/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-loading-text=\"");


            
            #line 47 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                          Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            data-confirm=\"");


            
            #line 48 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                     Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\"\n                            disabled=\"disabled\">\n                        <span " +
"class=\"glyphicon glyphicon-remove\"></span>\n                        ");


            
            #line 51 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                   Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral("\n                    </button>\n\n");


            
            #line 54 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                   if (true)
                  {
                      
            
            #line default
            #line hidden
            
            #line 56 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                 Write(Html.Filter(pager));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                         
                  }

            
            #line default
            #line hidden
WriteLiteral(@"                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th class=""min-width"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th class=""min-width"">");


            
            #line 67 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                 Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th>");


            
            #line 68 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                               Write(Strings.ScheduledJobsPage_Table_Enqueue);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                <th>");


            
            #line 69 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                               Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 70 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                 if (DisplayArgumentsInLists)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <th class=\"min-width\">");


            
            #line 72 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                     Write(Strings.Common_Arguments);

            
            #line default
            #line hidden
WriteLiteral("</th>\n");


            
            #line 73 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <th class=\"align-right\">");


            
            #line 74 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                   Write(Strings.ScheduledJobsPage_Table_Scheduled);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                            </tr>\n                        </thead>\n");


            
            #line 77 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                         foreach (var job in scheduledJobs)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row ");


            
            #line 79 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                    Write(!job.Value.InScheduledState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 79 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                                                                            Write(job.Value.InScheduledState ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                <td>\n");


            
            #line 81 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                     if (job.Value.InScheduledState)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input type=\"checkbox\" class=\"js-jobs-lis" +
"t-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 83 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                                                                             Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\n");


            
            #line 84 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\n                                <td class=\"" +
"min-width\">\n                                  ");


            
            #line 87 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                             Write(Html.JobNameLink(job.Key, monitor.JobDetails(job.Key).Properties["RecurringJobId"], job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 88 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                   if (!job.Value.InScheduledState)
                                  {

            
            #line default
            #line hidden
WriteLiteral("                                    <span title=\"");


            
            #line 90 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                            Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\n");


            
            #line 91 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                  }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\n");


            
            #line 93 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                 if (DisplayArgumentsInLists)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td class=\"ellipsis ellipsis-wrap\">\n         " +
"                                 ");


            
            #line 96 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                     Write(Html.JobArguments(job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                      </td>\n");


            
            #line 98 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <td class=\"min-width\">\n                          " +
"          ");


            
            #line 100 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                               Write(Html.RelativeTime(job.Value.EnqueueAt));

            
            #line default
            #line hidden
WriteLiteral("\n                                </td>\n                                <td class=" +
"\"word-break\">\n                                    ");


            
            #line 103 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                               Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                </td>\n                                <td class=" +
"\"align-right\">\n");


            
            #line 106 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                     if (job.Value.ScheduledAt.HasValue)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 108 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                   Write(Html.RelativeTime(job.Value.ScheduledAt.Value));

            
            #line default
            #line hidden
            
            #line 108 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                                                                                       
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\n                            </tr>\n");


            
            #line 112 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </table>\n                </div>\n\n              <div class=\"bt" +
"n-toolbar\">\n                  ");


            
            #line 117 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
             Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              \n                  ");


            
            #line 119 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
             Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\n              </div>\n            </div>\n");


            
            #line 122 "..\..\Dashboard\Pages\ScheduledJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>");


        }
    }
}
#pragma warning restore 1591
