// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsJobRunning_For_Scheduler_Tracking_Rugby_Fixtures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsJobRunning_For_Scheduler_Tracking_Rugby_Fixtures));
        
        string IMigrationMetadata.Id
        {
            get { return "201711102015027_IsJobRunning_For_Scheduler_Tracking_Rugby_Fixtures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
