// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Scheduling_Dashboard_Users_To_System_Sports_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Scheduling_Dashboard_Users_To_System_Sports_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201712130951576_Add_Scheduling_Dashboard_Users_To_System_Sports_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
