// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updates_To_Dashboard_Users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates_To_Dashboard_Users));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131126184_Updates_To_Dashboard_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
