// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Motorsport_Delete_Unused_TrackingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motorsport_Delete_Unused_TrackingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030816573_Motorsport_Delete_Unused_TrackingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
