// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Motorsport_SysDataTemp_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motorsport_SysDataTemp_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201802281026001_Motorsport_SysDataTemp_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
