// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.SystemSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Motorsport_RaceEvents_Tracking_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motorsport_RaceEvents_Tracking_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201804260714382_Motorsport_RaceEvents_Tracking_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
