// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_timestamps_for_created_and_updated_record_states : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_timestamps_for_created_and_updated_record_states));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261035297_Added_timestamps_for_created_and_updated_record_states"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
