// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_CMS_override_for_RugbyPlayer_DisplayName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_CMS_override_for_RugbyPlayer_DisplayName));
        
        string IMigrationMetadata.Id
        {
            get { return "201710250715016_Added_CMS_override_for_RugbyPlayer_DisplayName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
