// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_HasLogs_To_Rugby_Tournament : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_HasLogs_To_Rugby_Tournament));
        
        string IMigrationMetadata.Id
        {
            get { return "201711280810482_Add_HasLogs_To_Rugby_Tournament"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
