// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_RugbyCommentary_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_RugbyCommentary_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201709280717260_Added_RugbyCommentary_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
