// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Temporary_removal_of_legacyId_fields_for_rescaffolding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Temporary_removal_of_legacyId_fields_for_rescaffolding));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011236546_Temporary_removal_of_legacyId_fields_for_rescaffolding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
