// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Allow_Nulls_For_Team_Scores_In_RugbyFixture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Allow_Nulls_For_Team_Scores_In_RugbyFixture));
        
        string IMigrationMetadata.Id
        {
            get { return "201709210723349_Allow_Nulls_For_Team_Scores_In_RugbyFixture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
