// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingDatabaseGeneratedIdFor_RugbySeason_RugbyTournament : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingDatabaseGeneratedIdFor_RugbySeason_RugbyTournament));
        
        string IMigrationMetadata.Id
        {
            get { return "201709141040032_AddingDatabaseGeneratedIdFor_RugbySeason_RugbyTournament"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
