// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rescaffolded_RugbyLogGroup_and_rugby_events_related_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rescaffolded_RugbyLogGroup_and_rugby_events_related_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201710190823257_Rescaffolded_RugbyLogGroup_and_rugby_events_related_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
