// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Reference_To_RugbySeason_From_RugbyLogGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Reference_To_RugbySeason_From_RugbyLogGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281034310_Add_Reference_To_RugbySeason_From_RugbyLogGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
