// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Renamed_RugbyPlayerLineup_field_ShirtNumber_to_JerseyNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamed_RugbyPlayerLineup_field_ShirtNumber_to_JerseyNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021118075_Renamed_RugbyPlayerLineup_field_ShirtNumber_to_JerseyNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
