// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_DataProvider_RugbySeason_RugbyTournament_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_DataProvider_RugbySeason_RugbyTournament_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201709130824239_Added_DataProvider_RugbySeason_RugbyTournament_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
