// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_grouped_logs_tables_and_other_related_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_grouped_logs_tables_and_other_related_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261331301_Added_grouped_logs_tables_and_other_related_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
