// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Rugby_Add_DefaultRugbyLogType_RugbyTournament : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rugby_Add_DefaultRugbyLogType_RugbyTournament));
        
        string IMigrationMetadata.Id
        {
            get { return "201809031917128_Rugby_Add_DefaultRugbyLogType_RugbyTournament"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
