// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rugby_Added_Venue_Name_Cms_Override : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rugby_Added_Venue_Name_Cms_Override));
        
        string IMigrationMetadata.Id
        {
            get { return "201804170525526_Rugby_Added_Venue_Name_Cms_Override"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
