// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Rugby_MatchNumber_RoundName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rugby_MatchNumber_RoundName));
        
        string IMigrationMetadata.Id
        {
            get { return "201810241311354_Rugby_MatchNumber_RoundName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
