// <auto-generated />
namespace SuperSportDataEngine.Repository.EntityFramework.PublicSportData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Motorsport_league_navigtion_for_standings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motorsport_league_navigtion_for_standings));
        
        string IMigrationMetadata.Id
        {
            get { return "201803121435476_Motorsport_league_navigtion_for_standings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
